config/routes.rb
FormulatronApp::Application.routes.draw do
  resources :forms do
    resources :submissions
  end
   
  root :to => 'forms#index'
end

app/models/element.rb
# This class was originally called `Field`, however, this is a 
# keyword in Mongoid.
class Element
  extend ActiveSupport::Memoizable
  include Mongoid::Document
  field :name, type: String
  field :label, type: String
  field :element_type, type: String
  embedded_in :form
  embeds_many :options

  # These types correspond to the mappings in SimpleForm.
  # This allows us to get SimpleForm to render the correct type of field.
  TYPES = {
    string: 'Single Line Text',
    text: 'Paragraph Text',
    check_boxes: 'Checkboxes',
    radio: 'Multiple Choice'
  }

  validates_inclusion_of :element_type, in: Element::TYPES.keys.map(&:to_s)
  validates_presence_of :name, :label
  accepts_nested_attributes_for :options, :allow_destroy => true

  # TODO Have a clever method to work out the class and styles for different elements
  # e.g. text areas should have 3 rows.

  def check_box?
    element_type == 'check_boxes'
  end

  def radio?
    element_type == 'radio'
  end

  # Returns a hash of each option and its count.
  # Useful for quantitative values.
  def option_counts
    submissions = form.submissions
    
    values = Hash.new(0)
    submissions.each do |submission|
      submission.quantitative_values.each do |value|
        
        # Radio buttons only have one choice
        if value.content.is_a?(String)
          values[value.content] += 1
          next
        end

        # Checkboxes can have multiple choices
        value.content.each do |choice|
          values[choice] += 1
        end
      end
    end
    
    return values
  end
  memoize :option_counts

  protected

  # Sets the label attribute from the form value. We then downcase it, turn 
  # all the spaces into underscores, rip out any non-word characters and
  # assign it as the name attribute.
  #
  # We do this is because the user provides the label for the form field, but
  # they won't understand why they also need to provide a name.
  def label=(attribute)
    super
    self.name = label.downcase.tr(" ", "_").gsub(/\W/, '')
  end
end

app/models/form.rb
class Form
  include Mongoid::Document
  field :name, type: String
  field :description, type: String
  embeds_many :elements
  has_many :submissions

  validates_presence_of :name, :description
  accepts_nested_attributes_for :elements, :allow_destroy => true

  def quantitative_elements
    elements.any_in(element_type: ['check_boxes', 'radio'])
  end

  def qualitative_elements
    elements.any_in(element_type: ['string', 'text'])
  end
end

app/models/option.rb
class Option
  include Mongoid::Document
  field :value, type: String
  embedded_in :element

  def to_s
    value
  end
end

app/models/submission.rb
class Submission
  include Mongoid::Document
  include Mongoid::Timestamps
  belongs_to :form
  embeds_many :values
  # TODO validation
  accepts_nested_attributes_for :values

  def quantitative_values
    values.any_in(element_type: ['check_boxes', 'radio']).all
  end

  def qualitative_values
    values.any_in(element_type: ['string', 'text']).all
  end
end

app/models/value.rb
class Value
  include Mongoid::Document
  field :name
  field :content # Could be a string (text) or an array (checkboxes)
  field :element_type
  embedded_in :submission

  # This is pretty hacky.
  def method_missing(m, *args, &block)
    return ''
  end

  def to_s
    content
  end
  
  def content=(attribute)
    if attribute.is_a?(Array)
      # Remove any blank attributes sent via the form
      super(attribute.reject(&:blank?))
    else
      super # If we're dealing with a string just pass it up
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  def index
    @forms = Form.all
  end

  def show
    @form = Form.find params[:id]
    @submissions = @form.submissions

    @qualitative_elements   = @form.qualitative_elements
    @quantitative_elements  = @form.quantitative_elements
  end

  def new
    @form = Form.new
    @form.elements.build
  end

  def create
    @form = Form.new(params[:form])
    if @form.save
      redirect_to @form
    else
      render :new
    end
  end

  def edit
    @form = Form.find params[:id]
  end

  def update
    @form = Form.find params[:id]
    if @form.update_attributes params[:form]
      redirect_to @form
    else
      render :new
    end
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  def new
    @form = Form.find params[:form_id]
    @submission = @form.submissions.build
  end

  def create
    @form = Form.find params[:form_id]
    @submission = @form.submissions.build params[:submission]

    if @submission.save
      redirect_to @form
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)", class: 'btn small danger')
  end
  
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")", class: 'btn small primary')
  end
end

app/helpers/forms_helper.rb
module FormsHelper
  def percentage(total, count)
    return "0" if total.zero?
    "%.0f" % ((count.to_f / total.to_f) * 100)
  end

  def total(count, element)
    if element.check_box?
      "Total Entries: #{count}"
    else
      "Total: #{count}"
    end
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/forms/_element_fields.html.haml
- f.object.options.build unless f.object.options.any?

.clearfix
  = f.input :label
  = f.input :element_type, collection: Element::TYPES.map {|t| [t[1], t[0]]}, label: "Type", include_blank: false

  %fieldset.options
    %legend Choices
    = f.simple_fields_for :options do |option_form|
      = render partial: 'option_fields', :locals => { :f => option_form }
    %p= link_to_add_fields "Add Choice", f, :options

  = link_to_remove_fields "Remove Field", f
  %br
  %hr

app/views/forms/_field_fields.html.haml
.clearfix
  = f.label :name, "Name"
  .input
    = f.text_field :name
.clearfix
  = f.label :type, "Type"
  .input
    = f.select :type, Field::TYPES.collect { |t| [t.humanize, t.to_s] }

= link_to_remove_fields "remove", f

app/views/forms/_form.html.haml
= simple_form_for @form do |f|
  = render "shared/error_messages", :target => @form

  %fieldset
    = f.input :name, label: "Form Name", input_html: { class: 'xxlarge' }
    = f.input :description, :as => :text, input_html: { class: 'xxlarge', rows: 3 }
  %hr
  %fieldset
    %legend Fields

    = f.simple_fields_for :elements do |element_form|
      = render partial: 'element_fields', :locals => { :f => element_form }
    %p= link_to_add_fields "Add Field", f, :elements

  %fieldset
    .actions
      = f.button :submit, class: 'btn primary'
      = link_to "Cancel", root_path, class: "btn"

app/views/forms/_option_fields.html.haml
.clearfix
  = f.label :value
  = f.input_field :value
  = link_to_remove_fields "Remove choice", f

app/views/forms/_qualitative_elements.html.haml
%table
  %thead
    %tr
      %th #
      - @qualitative_elements.collect(&:label).each do |element_label|
        %th
          = element_label
      %th Date
  %tbody
    - @submissions.each_with_index do |submission, index|
      %tr
        %td=index+1
        - @qualitative_elements.collect(&:name).each do |name|
          %td
            = submission.values.where(name: name).first
        %td=submission.created_at.to_s(:long_ordinal)

app/views/forms/_quantitative_element.html.haml
%h2=element.label

%table
  %thead
    %tr
      %th Choices
      %th Percentage
      %th Count

  %tbody
    - element.options.each do |option|
      - option_count = element.option_counts[option.value]
      %tr
        %td=option
        %td
          - percent = percentage(@submissions.count, option_count)
          .meter
            %span{style: "width: #{percent}%", class: "#{cycle('', 'red', 'green')}"}
              %p
                ="#{percent}%"
        %td= option_count

%h3
  = total(@submissions.count, element)

app/views/forms/edit.html.haml
= render 'form'

app/views/forms/index.html.haml
%h1 Forms

%ul
  - @forms.each do |form|
    %li
      %p= form.name
      %p
        = link_to 'Edit', edit_form_path(form)
        |
        = link_to "See results", form
        |
        = link_to "Submit response", new_form_submission_path(form)

= link_to "Create new form", new_form_path

app/views/forms/new.html.haml
= render 'form'

app/views/forms/show.html.haml
%h2 Responses

- if @qualitative_elements.any?
  = render partial: 'qualitative_elements'

= render partial: 'quantitative_element', collection: @quantitative_elements, :as => :element

= link_to 'Back to forms', forms_path

app/views/layouts/application.html.haml
!!! 5

%html
  %head
    %title
      FormulatronApp
    = stylesheet_link_tag    "application"
    = stylesheet_link_tag "http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .topbar
      .fill
        .container
          = link_to "Formulatron", root_path, class: "brand"
          %ul.nav
            %li.active
              = link_to 'Home', root_path
            %li
              = link_to "About", '#'
            %li
              = link_to "Contact", '#'

    .container
      .content
        .page-header
          %h1
            Formulatron App
            %small Test application to showoff Formulatron
        .row
          .span14
            - if notice
              .alert-message.notice
                %p= notice
            - if alert
              .alert-message.alert
                %p= alert
            
            = yield
            
      %footer
        %p Tony Daly 2011
      

app/views/shared/_error_messages.html.haml
- if target.errors.any?
  .alert-message.block-message.error
    %strong
      Some errors were found, please take a look:

    %ul
      - target.errors.full_messages.each do |msg|
        %li= msg

app/views/submissions/new.html.haml
%h2=@form.name
%p=@form.description

= simple_form_for [@form, @submission] do |f|
  - @form.elements.each_with_index do |element, index|

    = f.simple_fields_for :values, f.object.values.build do |value_form|
      = value_form.input :content, 
        as: element.element_type.to_sym,
        collection: element.options.collect(&:value),
        label: element.label, 
        input_html: { class: "element.options.any? ? '' : xxlarge'" }
      = value_form.input :name, input_html: { value: element.name }, :as => :hidden
      = value_form.input :element_type, input_html: { value: element.element_type }, :as => :hidden

  = f.button :submit, class: 'btn primary'

= link_to 'Back to forms', forms_path